### ISSUE TITLE
Add XCTest, CI and coverage

### ISSUE THREAD

**Issue by rraallvv** [PedestrianSean/ObjC-Lua#3]
I'd like to suggest adding XCTest to be able to run each test individual and get the corresponding coverage, I was able to do that in [my fork](https://github.com/rraallvv/ObjC-Lua), I'd be happy to push those to the upstream :)

**Comment by PedestrianSean** [comment]
Send me a pull request & I'll take a look.

**Comment by rraallvv** [comment]
[Here you go](https://github.com/PedestrianSean/ObjC-Lua/pull/4)
